server:
  port: 8080
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: #{HOME}/Desktop/config
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuan-linker/config-repo
          username: username
          password: password